#ifndef COMPONENTS_STATE_MACHINE_COMMON_H_
#define COMPONENTS_STATE_MACHINE_COMMON_H_

#include <stdint.h>

typedef enum {
    SM_EVENT_SYSTEM_READY = 0,
    SM_EVENT_HALT,
    SM_EVENT_PUMP_ON,
    SM_EVENT_PUMP_OFF,
    SM_EVENT_NOZZLE_EXTEND,
    SM_EVENT_NOZZLE_EXTEND_FULL,
    SM_EVENT_NOZZLE_RETRACT,
    SM_EVENT_NOZZLE_RETRACT_FULL,
    SM_EVENT_STOP_SPOOL,
    SM_EVENT_UPPER_LIMIT_ACTIVE,
    SM_EVENT_UPPER_LIMIT_RELEASED,
    SM_EVENT_LOWER_LIMIT_ACTIVE,
    SM_EVENT_LOWER_LIMIT_RELEASED,
    SM_EVENT_RC_SIGNAL_LOST,
    SM_EVENT_FAULT,
    SM_EVENT_RESET
} StateMachineEventId_t;

typedef enum {
    STATE_MACHINE_INIT = 0,
    STATE_MACHINE_STOWED,
    STATE_MACHINE_LOWERING,
    STATE_MACHINE_DEPLOYED,
    STATE_MACHINE_PUMPING,
    STATE_MACHINE_RAISING,
    STATE_MACHINE_POSITION_UNKNOWN,
    STATE_MACHINE_FAULT
} StateMachineState_t;


typedef struct {
    StateMachineEventId_t eId;
    uint32_t ulData;
} StateMachineEvent_t;

const char* stateMachineEventName(StateMachineEvent_t sEvent);

const char* StateMachineStateName(StateMachineState_t eState);

#endif /* COMPONENTS_STATE_MACHINE_COMMON_H_ */
